config/routes.rb
NinetyNineCatsDay1::Application.routes.draw do

  resource :user, only: [:create, :new, :destroy]
  resource :session, only: [:create, :new, :destroy]

  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end

  root to: redirect("/cats")
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :user_name, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    session_token
  end

  def generate_session_token
    SecureRandom::urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
    # session_token = session_token || generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    user if user && user.is_password?(password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    # @user.password=(params[:user][:password])
    if @user.save
      login_user!
    else
      # debugger
      flash.now[:notice] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>
<input type="hidden" name="session_token" value="<%= @current_user.session_token %>">

app/views/users/new.html.erb
<h1>Registration</h1>
<form action="<%= user_url %>" method="post">
  <input type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <input type="text"
  name="user[user_name]"
  value="<%= @user.user_name %>"
  placeholder="username">

  <input type="password"
  name="user[password]"
  placeholder="password">
  <input type="submit" value="Create User">

</form>